### ISSUE TITLE
Jenkins issues

### ISSUE THREAD

**Issue by jchodera** [choderalab/conda-recipes#4]
I'm running into this error:

```
[BinstarError] Can not create package 
Traceback (most recent call last):
  File "/home/vagrant/miniconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 185, in main
    add_package(binstar, args, username, package_name, package_attrs, package_type)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 114, in add_package
    public=True)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 269, in add_package
    self._check_response(res)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 160, in _check_response
    raise ErrCls(msg, res.status_code)
BinstarError: (u'Can not create package', 400)
```

Not quite sure what it is due to.

Full output here:
https://jenkins.choderalab.org/job/choderalab-conda-release-linux/5/console

**Comment by danielparton** [comment]
Looks like the `conda-build-all --upload` flag should be changed from `omnia` to `choderalab`.
From the Jenkins log:

```
+ vagrant ssh --command 'cd conda-recipes ; BINSTAR_TOKEN=**** ./conda-build-all --upload omnia --check-against choderalab ./*'
```

**Comment by jchodera** [comment]
D'oh.  I thought I had got all of those.

**Comment by jchodera** [comment]
Huzzah!  We have (linux) packages!

**Comment by danielparton** [comment]
Thanks!
